### ISSUE TITLE
Objects aren't always saved correctly

### ISSUE THREAD

**Issue by SMWW4mp3** [Yoshimaster96/Superstar-Editor-SMW#5] opened 2020-08-30 21:04 UTC
Sometimes the editor saves objects not correctly:
![sesmw_4](https://user-images.githubusercontent.com/28955730/91668779-8f557280-eb0f-11ea-9245-df2439e060d1.png)

Here the comparison before I reloaded the level and after reloading the level (ignore that the timestamp from before is bigger than the after timestamp):
![sesmw_5](https://user-images.githubusercontent.com/28955730/91668983-82d21980-eb11-11ea-8edc-18d76ab622de.png)

Curiously the objects that get modified are always incremented by one (06 Dirt → 07 Water tiles 2; 14 Ledge → 15 Midway Point/Goal Point; 12 Gradual Slope → 13 Solid right+top edge; 0A Coin blocks → 0B Throw blocks)

I couldn't replicate this behaviour reliably, it some times does that, other times it doesn't. Here's the most reliable setup I could find (still not happening always):
![sesmw_6](https://user-images.githubusercontent.com/28955730/91669303-2de3d280-eb14-11ea-811d-03f9a9103cf0.png)

Btw. this is the same level from Issue #4 but I couldn't figure it out how to replicate this until now.

**Comment by Yoshimaster96** [comment] 2020-08-31 23:04
Hm, I'll take a look, thanks for letting me know.

**Comment by Yoshimaster96** [comment] 2020-09-01 17:27
This might be an issue with the `romAlloc` function (this issue was fixed in 1.1). I'll check to see if that's what the problem is. If so, it's an easy fix, I can just copy the code over.

**Closed** 2020-09-05 22:01 UTC
Labels: bug, cantreproduce
